Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Controllers/LogController.cs
using System;
using System.Web.Mvc;

namespace AnvilGroup.Applications.Fit2Work.Controllers {
    public class LogController : BaseController {

        // GET: Log
        public ActionResult Index(DateTime? date = null, int pageNumber = 1, int maxPerPage = 25) {

            if (!date.HasValue) {
                date = DateTime.UtcNow;
            }

            ViewBag.Date = date;
            ViewBag.pageNumber = pageNumber;
            ViewBag.maxPerPage = maxPerPage;
            ViewBag.LogCount = LoggingService.GetLogCount(date.Value);

            return View(LoggingService.GetLogs(date.Value, pageNumber, maxPerPage));
        }

        // GET: Details
        public ActionResult Details(int id) {
            return View(LoggingService.GetLogById(id));
        }
    }
}

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Controllers/ResourceUrlsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AnvilGroup.Services.Fit2Work.Data;
using AnvilGroup.Services.Fit2Work.Models;

namespace AnvilGroup.Applications.Fit2Work.Controllers {
    public class ResourceUrlsController : BaseController {
        // GET: ResourceUrls
        public ActionResult Index() {
            return View(Fit2WorkDb.ResourceUrls.ToList());
        }

        // GET: ResourceUrls/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResourceUrlModel resourceUrlModel = Fit2WorkDb.ResourceUrls.Find(id);
            if (resourceUrlModel == null) {
                return HttpNotFound();
            }
            return View(resourceUrlModel);
        }

        // GET: ResourceUrls/Create
        public ActionResult Create() {
            return View();
        }

        // POST: ResourceUrls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CultureCode,Name,Url")] ResourceUrlModel resourceUrlModel) {
            if (ModelState.IsValid) {
                Fit2WorkDb.ResourceUrls.Add(resourceUrlModel);
                Fit2WorkDb.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(resourceUrlModel);
        }

        // GET: ResourceUrls/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResourceUrlModel resourceUrlModel = Fit2WorkDb.ResourceUrls.Find(id);
            if (resourceUrlModel == null) {
                return HttpNotFound();
            }
            return View(resourceUrlModel);
        }

        // POST: ResourceUrls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CultureCode,Name,Url")] ResourceUrlModel resourceUrlModel) {
            if (ModelState.IsValid) {
                var resourceUrl = Fit2WorkDb.ResourceUrls
                    .SingleOrDefault(r => r.Id == resourceUrlModel.Id);
                resourceUrl.Name = resourceUrlModel.Name;
                resourceUrl.Url = resourceUrlModel.Url;
                Fit2WorkDb.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(resourceUrlModel);
        }

        // GET: ResourceUrls/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResourceUrlModel resourceUrlModel = Fit2WorkDb.ResourceUrls.Find(id);
            if (resourceUrlModel == null) {
                return HttpNotFound();
            }
            return View(resourceUrlModel);
        }

        // POST: ResourceUrls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            ResourceUrlModel resourceUrlModel = Fit2WorkDb.ResourceUrls.Find(id);
            Fit2WorkDb.ResourceUrls.Remove(resourceUrlModel);
            Fit2WorkDb.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
    }
}

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Controllers/UserController.cs
using System.Web.Mvc;

namespace AnvilGroup.Applications.Fit2Work.Controllers {
    public class UserController : BaseController {
        // GET: User
        public ActionResult Index(int pageNumber = 1, int maxPerPage = 25) {
            
            ViewBag.pageNumber = pageNumber;
            ViewBag.maxPerPage = maxPerPage;
            ViewBag.UserCount = UserService.GetUserCount();

            return View(UserService.GetUsers(pageNumber, maxPerPage));
        }
        // GET: Details
        public ActionResult Details(int id) {
            ViewBag.UserQuestionnaires = UserService.GetUserQuestionnaires(id);
            return View(UserService.GetUserById(id));
        }
    }
}

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fit To Work - Administration</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            @Html.ActionLink("Fit To Work", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Clients", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Users", "Index", "User", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Resources", "Index", "Resources", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Resource Urls", "Index", "ResourceUrls", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Daily Logs", "Index", "Log", new { area = "", date = DateTime.UtcNow, pageNumber = 1, maxPerPage = 25 }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>    
    <div class="container body-content">
        <div id="globalAlert" class="alert alert-dismissible" role="alert" style="display:none;">
            <button type="button" class="close" data-hide="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p id="globalAlertMessage"></p>
        </div>
        <div class="clearmed"></div>
        @RenderBody()
        <div class="clearmed"></div>
        <hr />
        <footer>
            <div class="copyright">
                &copy; @DateTime.UtcNow.Year <a href="http://www.anvilgroup.com/">The Anvil Group</a> (International) Ltd
                <div class="clear"></div>
                <span class="small">v @Html.Raw(typeof(AnvilGroup.Applications.Fit2Work.MvcApplication).Assembly.GetName().Version)</span>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>