Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Controllers/ClientController.cs
using System;
using System.Web.Mvc;
using AnvilGroup.Services.Fit2Work.Models;

namespace AnvilGroup.Applications.Fit2Work.Controllers {
    public class ClientController : BaseController {
        public ClientController() : base() { }
        // GET: Client
        public ActionResult Index() {
            return View();
        }

        // GET: Client/Details/5
        public ActionResult Details(int id) {
            var client = ClientService.GetClientById(id);
            SetClientViewBag(id);
            return View(client);
        }

        // GET: Client/Create
        public ActionResult Create() {
            return View(new ClientModel());
        }

        // POST: Client/Create
        [HttpPost]
        public ActionResult Create(ClientModel client) {
            if (!ModelState.IsValid)
            {
                return View(client);
            }
            if (!ClientService.IsMemberCodeUnique(client))
            {
                ModelState.AddModelError("MemberCode", $"Member code {client.MemberCode} is not unique.");
                return View(client);
            }
            try
            {
                ClientService.CreateClient(client);
                return RedirectToAction("Details", new { id = client.Id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error:  {ex.Message} is not unique.");
                return View(client);
            }

            return View();
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int id) {
            return View(ClientService.GetClientById(id));
        }

        // POST: Client/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ClientModel client) {
            if (!ModelState.IsValid) {
                return View(client);
            }
            if (!ClientService.IsMemberCodeUnique(client)) {
                ModelState.AddModelError("MemberCode", $"Member code {client.MemberCode} is not unique.");
                return View(client);
            }
            try {
                ClientService.UpdateClient(id, client);
                client.Users = UserService.GetUsersByClientId(client.Id);
                SetClientViewBag(id);
                return View("Details", client);
            } catch (Exception ex) {
                ModelState.AddModelError(string.Empty, $"Error:  {ex.Message}.");
                return View(client);
            }
        }

        private void SetClientViewBag(int clientId) {
            ViewBag.RegiseredUserCount = UserService.RegisteredUserCountByClientId(clientId);
            ViewBag.QuestionnareDailyCount = UserService.DailyQuestionnaireCountByClientId(clientId);
            ViewBag.QuestionnareTotalCount = UserService.TotalQuestionnaireCountByClientId(clientId);
            ViewBag.AllowSelectUsers = true;
        }
    }
}

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Controllers/UserController.cs
using System.Web.Mvc;

namespace AnvilGroup.Applications.Fit2Work.Controllers {
    public class UserController : BaseController {
        // GET: User
        public ActionResult Index(int pageNumber = 1, int maxPerPage = 25) {
            
            ViewBag.pageNumber = pageNumber;
            ViewBag.maxPerPage = maxPerPage;
            ViewBag.UserCount = UserService.GetUserCount();

            return View(UserService.GetUsers(pageNumber, maxPerPage));
        }
        // GET: Details
        public ActionResult Details(int id) {
            ViewBag.UserQuestionnaires = UserService.GetUserQuestionnaires(id);
            return View(UserService.GetUserById(id));
        }
    }
}

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Views/User/Details.cshtml
@using AnvilGroup.Services.Fit2Work.Models
@model UserInfoModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User details</h2>
<div class="row">
    <div class="col-md-6">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                User Id
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IsDeleted)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SmsSentDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SmsSentDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RegisteredDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RegisteredDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UpdatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UpdatedDate)
            </dd>
        </dl>
        <p>
            @Html.ActionLink("View all users", "Index", "User", null, new { @class = "btn btn-primary" })
        </p>
    </div>
    <div class="col-md-6">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ClientId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ClientId)
            </dd>

            <dt>
                Client
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Client.Name)
            </dd>
        </dl>
        <p>
            @Html.ActionLink("View Client", "Details", "Client", new { id = Model.ClientId }, new { @class = "btn btn-primary" })
        </p>
    </div>
</div>
<div class="clearmed"><hr/></div>
<div class="row">
    <div class="col-md-12">
        @Html.Partial("Partials/_QuestionnaireList", (IEnumerable<UserQuestionnaireModel>)ViewBag.UserQuestionnaires)
    </div>
</div>

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Views/User/Index.cshtml
@using AnvilGroup.Services.Fit2Work.Models
@model List<UserInfoModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("Partials/_UserList", Model)