Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Controllers/ResourcesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AnvilGroup.Services.Fit2Work.Data;
using AnvilGroup.Services.Fit2Work.Models;

namespace AnvilGroup.Applications.Fit2Work.Controllers {
    public class ResourcesController : BaseController {

        public ResourcesController() : base() { }

        // GET: Resources
        public ActionResult Index() {
            return View(Fit2WorkDb.Resources.ToList());
        }

        // GET: Resources/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResourceModel resourceModel = Fit2WorkDb.Resources.Find(id);
            if (resourceModel == null) {
                return HttpNotFound();
            }
            return View(resourceModel);
        }

        // GET: Resources/Create
        public ActionResult Create() {
            return View();
        }

        // POST: Resources/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CultureCode,EmailHeader,EmailFooter," +
            "PrimaryEmailSubject,PrimaryEmailBody," +
            "SecondaryEmailSubject,SecondaryEmailBody," +
            "UserMessageText,UserPrimaryMessageText,UserSecondaryMessageText")]
            ResourceModel resourceModel) {
            if (ModelState.IsValid) {
                Fit2WorkDb.Resources.Add(resourceModel);
                Fit2WorkDb.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(resourceModel);
        }

        // GET: Resources/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResourceModel resourceModel = Fit2WorkDb.Resources.Find(id);
            if (resourceModel == null) {
                return HttpNotFound();
            }
            return View(resourceModel);
        }

        // POST: Resources/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CultureCode,EmailHeader,EmailFooter," +
            "PrimaryEmailSubject,PrimaryEmailBody," +
            "SecondaryEmailSubject,SecondaryEmailBody," +
            "UserMessageText,UserPrimaryMessageText,UserSecondaryMessageText,DownloadMessageText")]
        ResourceModel resourceModel) {
            if (ModelState.IsValid) {
                var resources = Fit2WorkDb.Resources
                    .SingleOrDefault(r => r.Id == resourceModel.Id);
                resources.EmailHeader = resourceModel.EmailHeader;
                resources.EmailFooter = resourceModel.EmailFooter;
                resources.PrimaryEmailSubject = resourceModel.PrimaryEmailSubject;
                resources.PrimaryEmailBody = resourceModel.PrimaryEmailBody;
                resources.SecondaryEmailSubject = resourceModel.SecondaryEmailSubject;
                resources.SecondaryEmailBody = resourceModel.SecondaryEmailBody;
                resources.UserMessageText = resourceModel.UserMessageText;
                resources.UserPrimaryMessageText = resourceModel.UserPrimaryMessageText;
                resources.UserSecondaryMessageText = resourceModel.UserSecondaryMessageText;
                resources.DownloadMessageText = resourceModel.DownloadMessageText;
                Fit2WorkDb.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(resourceModel);
        }

        // GET: Resources/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResourceModel resourceModel = Fit2WorkDb.Resources.Find(id);
            if (resourceModel == null) {
                return HttpNotFound();
            }
            return View(resourceModel);
        }

        // POST: Resources/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            ResourceModel resourceModel = Fit2WorkDb.Resources.Find(id);
            Fit2WorkDb.Resources.Remove(resourceModel);
            Fit2WorkDb.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {            
            base.Dispose(disposing);
        }
    }
}

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Views/Resources/Create.cshtml
@model AnvilGroup.Services.Fit2Work.Models.ResourceModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>[Create] New Resources</h2>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CultureCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CultureCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CultureCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailHeader, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmailHeader, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmailHeader, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailFooter, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmailFooter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmailFooter, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrimaryEmailSubject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrimaryEmailSubject, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PrimaryEmailSubject, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrimaryEmailBody, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrimaryEmailBody, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PrimaryEmailBody, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SecondaryEmailSubject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SecondaryEmailSubject, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SecondaryEmailSubject, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SecondaryEmailBody, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SecondaryEmailBody, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SecondaryEmailBody, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserMessageText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserMessageText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserMessageText, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DownloadMessageText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DownloadMessageText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DownloadMessageText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserPrimaryMessageText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserPrimaryMessageText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserPrimaryMessageText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserSecondaryMessageText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserSecondaryMessageText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserSecondaryMessageText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "Index", "Resources", null, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Views/Resources/Delete.cshtml
@model AnvilGroup.Services.Fit2Work.Models.ResourceModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ResourceModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CultureCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CultureCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailHeader)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailHeader)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailFooter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailFooter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimaryEmailSubject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrimaryEmailSubject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimaryEmailBody)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrimaryEmailBody)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondaryEmailSubject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondaryEmailSubject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondaryEmailBody)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondaryEmailBody)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserMessageText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserMessageText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserPrimaryMessageText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserPrimaryMessageText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserSecondaryMessageText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserSecondaryMessageText)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Views/Resources/Details.cshtml
@model AnvilGroup.Services.Fit2Work.Models.ResourceModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>[View] | @Model.CultureCode Resources</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CultureCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CultureCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailHeader)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailHeader)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailFooter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailFooter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimaryEmailSubject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrimaryEmailSubject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimaryEmailBody)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrimaryEmailBody)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondaryEmailSubject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondaryEmailSubject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondaryEmailBody)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondaryEmailBody)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserMessageText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserMessageText)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DownloadMessageText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DownloadMessageText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserPrimaryMessageText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserPrimaryMessageText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserSecondaryMessageText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserSecondaryMessageText)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-success" })
    @Html.ActionLink("<< Back to List", "Index", null, new { @class = "btn btn-primary" })
</p>

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Views/Resources/Edit.cshtml
@model AnvilGroup.Services.Fit2Work.Models.ResourceModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>[Edit] | @Model.CultureCode Resources</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CultureCode)

    <div class="form-group">
        <strong>Current placeholders are: </strong>
        <ul>
            <li>{clientName} - client's company name (i.e. AnvilGroup)</li>
            <li>{memberCode} - client's member code (i.e. anvilgroup)</li>
            <li>{firstName} - user's first name</li>
            <li>{lastName} - user's last name</li>
            <li>{header} - the contents of the EmailHeader field for use within HTML email sent to clients</li>
            <li>{footer} - the contents of the EmailFooter field for use within HTML email sent to clients</li>
            <li>{AppleAppStoreUrl} - The url for the iOS app store</li>
            <li>{GooglePlayStoreUrl} - The url for the Android app store</li>
        </ul>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailHeader, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.EmailHeader, 10, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EmailHeader, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailFooter, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.EmailFooter, 10, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EmailFooter, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrimaryEmailSubject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.PrimaryEmailSubject, 2, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PrimaryEmailSubject, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrimaryEmailBody, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.PrimaryEmailBody, 10, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PrimaryEmailBody, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SecondaryEmailSubject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.SecondaryEmailSubject, 2, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SecondaryEmailSubject, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SecondaryEmailBody, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.SecondaryEmailBody, 10, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SecondaryEmailBody, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserMessageText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.UserMessageText, 5, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserMessageText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DownloadMessageText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.DownloadMessageText, 5, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DownloadMessageText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserPrimaryMessageText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.UserPrimaryMessageText, 5, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserPrimaryMessageText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserSecondaryMessageText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.UserSecondaryMessageText, 5, 300, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserSecondaryMessageText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Cancel", "Details", "Resources", new { id = Model.Id }, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}

Fit2WorkApiSolution/Fit2WorkApiSolution/Fit2Work/Views/Resources/Index.cshtml
@model IEnumerable<AnvilGroup.Services.Fit2Work.Models.ResourceModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <h2>Resources</h2>
        @Html.ActionLink("Create New Resources", "Create", "Resources", null, new { @class = "btn btn-primary" })
        <div class="clearmed"></div>
        <table class="table table-striped table-sm">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CultureCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserMessageText)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserPrimaryMessageText)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PrimaryEmailSubject)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserSecondaryMessageText)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SecondaryEmailSubject)
                </th>
                <th>Actions</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CultureCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserMessageText)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserPrimaryMessageText)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PrimaryEmailSubject)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserSecondaryMessageText)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SecondaryEmailSubject)
                    </td>
                    <td>
                        @Html.ActionLink("View", "Details", new { id = item.Id })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>